version: "3.8"
services:
  backend:
    container_name: "backend"
    image: node:18-slim
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 8080:8080
    environment:
      ES_URL: $ES_URL
    command: yarn dev

  frontend:
    container_name: "frontend"
    image: node:18-slim
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    links:
      - backend
    depends_on:
      backend:
        condition: service_started
    command: yarn start
